/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'Demo.Debug+IP-Stack' 
 * Target:  'Debug+IP-Stack' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "fsl_device_registers.h"

/* ARM::CMSIS-Compiler:STDERR:Custom@1.0.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
        #define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.0.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
        #define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.0.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
        #define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS-View:Event Recorder&DAP@1.5.3 */
#define RTE_CMSIS_View_EventRecorder
        #define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@10.4.6 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@10.4.6 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@10.4.6 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@10.4.6 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_5@10.4.6 */
#define RTE_RTOS_FreeRTOS_HEAP_5        /* RTOS FreeRTOS Heap 5 */
/* ARM::RTOS&FreeRTOS:Stream Buffer@10.4.6 */
#define RTE_RTOS_FreeRTOS_STREAM_BUFFER /* RTOS FreeRTOS Stream Buffers */
/* ARM::RTOS&FreeRTOS:Timers@10.4.6 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* ARM::Security:mbed TLS@2.24.0 */
#define RTE_Security_mbedTLS            /* Security mbed TLS */
/* Keil::CMSIS Driver:Ethernet MAC@1.6.0 */
#define RTE_Drivers_ETH_MAC0    (1U)    /* Driver ETH_MAC0 */
/* Keil::CMSIS Driver:Ethernet PHY:KSZ8081RNA@6.3.0 */
#define RTE_Drivers_PHY_KSZ8081RNA      /* Driver PHY KSZ8081RNA/RND */
/* Keil::CMSIS Driver:MCI@1.5.0 */
#define RTE_Drivers_MCI0        (1U)    /* Driver MCI0 */
        #define RTE_Drivers_MCI1        (1U)    /* Driver MCI1 */
/* Keil::CMSIS Driver:VIO:Board&IMXRT1050-EVKB@2.0.0 */
#define RTE_VIO_BOARD
        #define RTE_VIO_IMXRT1050_EVKB
/* MDK-Packs::IoT Utility:Socket:Custom@1.0.0 */
#define RTE_IoT_Socket                  /* IoT Socket */
/* NXP::Board Support:SDK Project Template:project_template&evkbimxrt1050@1.0.0 */
#ifndef XIP_EXTERNAL_FLASH
#define XIP_EXTERNAL_FLASH 1
#endif
#ifndef XIP_BOOT_HEADER_ENABLE
#define XIP_BOOT_HEADER_ENABLE 1
#endif
/* NXP::Device:SDK Drivers:codec@2.3.1 */
#ifndef SDK_I2C_BASED_COMPONENT_USED
#define SDK_I2C_BASED_COMPONENT_USED 1
#endif
/* NXP::Device:SDK Drivers:codec_i2c@2.1.0 */
#ifndef SDK_I2C_BASED_COMPONENT_USED
#define SDK_I2C_BASED_COMPONENT_USED 1
#endif
/* NXP::Device:SDK Drivers:wm8960@2.2.2 */
#ifndef SDK_I2C_BASED_COMPONENT_USED
#define SDK_I2C_BASED_COMPONENT_USED 1
#endif
#ifndef BOARD_USE_CODEC
#define BOARD_USE_CODEC 1
#endif
#ifndef CODEC_WM8960_ENABLE
#define CODEC_WM8960_ENABLE 
#endif
/* NXP::Device:SDK Utilities:serial_manager_uart@1.0.0 */
#ifndef SERIAL_PORT_TYPE_UART
#define SERIAL_PORT_TYPE_UART 1
#endif


#endif /* RTE_COMPONENTS_H */
