/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0
 *
 * Project: 'Demo.Release+WiFi' 
 * Target:  'Release+WiFi' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common:1.1.0 */
#define USE_HAL_DRIVER
/* Keil::Device:STM32Cube LL:Common:1.1.0 */
#define USE_FULL_LL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
